services:


  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      - provedor
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-mail

  asa-mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    hostname: mail.neopolis.asa.br
    ports: 
      - "25:25/tcp"
      - "587:587/tcp"
      - "110:110/tcp"
      - "143:143/tcp"
    container_name: asa-mail
    networks:
      - provedor
    volumes: 
      - mail:/var/mail


  roundcubedb:
    image: mysql:latest
    container_name: roundcubedb
#    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail
    networks:
      - provedor

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - roundcube:/var/www/html
    ports:
      - 9001:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail.neopolis.asa.br
      - ROUNDCUBEMAIL_SMTP_SERVER=mail.neopolis.asa.br
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
    networks:
      - provedor

volumes:
  mail:
  roundcube:
  db:
    




networks:
  provedor:
    driver: bridge